In [5]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy import dot
from numpy.linalg import eig

# numpy配列を定義します。
A = array([[1, 2], [3, 4], [5, 6]])
print('Aの行列：---------')
print(A)
print('')
print('A.T（Aの転置行列）：---------')
print(A.T)
print('')

#　A行列の縦方向の平均を求めます。
M = mean(A.T, axis=1)
print('M（=A.Tでaxis=1）A行列を転置して、横軸の平均値を取得する：---------')
print(M)
print('')

M1 = mean(A, axis=0)
print('M1（=Aでaxis=0）A行列を転置しないで、縦軸の平均値を取得する：---------')
print(M1)
print('')

# 平均との差を取得します。分散値を取得します。
C = A - M
print('C = A - M　ブロードキャストを利用して平均値との差を取得：---------')
print(C)
print('')

C1 = A - M1
print('C1 = A - M1　ブロードキャストを利用して平均値との差を取得：---------')
print(C1)
print('')

print('Cの転置行列：---------')
print(C.T)
print('')


# 共分散行列を取得します。 
#　numpy.covは、共分散を求めてくれる関数です
#　共分散というのは、二組の対応するデータがどれほどお互いに影響を持ちながら散らばっているかを表します。
V = cov(C.T)
print('V = cov(C.T)共分散行列を求める：---------')
print(V)
print('')

# 共分散行列の固有値・固有ベクトル分解
#　eig(a)は、配列を受け取り、固有値と固有ベクトル、2つのベクトルを返します。
values, vectors = eig(V)
print('values, vectors = eig(V)共分散行列の固有値分解：---------')
print('values（固有値）：---------')
print(values)
print('')

print('vectors（固有ベクトル）：---------')
print(vectors)
print('')

# 固有値ベクトルと、Cの転置とのドット積
print('P = dot(vectors.T, C.T)：---------')
P = dot(vectors.T, C.T)
print(P.T)


Aの行列：---------
[[1 2]
 [3 4]
 [5 6]]

A.T（Aの転置行列）：---------
[[1 3 5]
 [2 4 6]]

M（=A.Tでaxis=1）A行列を転置して、横軸の平均値を取得する：---------
[ 3.  4.]

M1（=Aでaxis=0）A行列を転置しないで、縦軸の平均値を取得する：---------
[ 3.  4.]

C = A - M　ブロードキャストを利用して平均値との差を取得：---------
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

C1 = A - M1　ブロードキャストを利用して平均値との差を取得：---------
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

Cの転置行列：---------
[[-2.  0.  2.]
 [-2.  0.  2.]]

V = cov(C.T)共分散行列を求める：---------
[[ 4.  4.]
 [ 4.  4.]]

values, vectors = eig(V)共分散行列の固有値分解：---------
values（固有値）：---------
[ 8.  0.]

vectors（固有ベクトル）：---------
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

P = dot(vectors.T, C.T)：---------
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [35]:
tomo = np.array([[2,2],[4,4]])

In [40]:
tomo -np.array([2,1])

array([[0, 1],
       [2, 3]])